# Book settings
title: Python extra slides
author: Thierry Parmentelat
logo: ../media/inria-50-alpha.png

latex:
  latex_documents:
    targetname: book.tex
  latex_engine: xelatex

# cannot use the cache strategy here
# because the reference to ../data/ 
# won't work in cache mode
execute:
#  execute_notebooks: auto
  execute_notebooks: force
