# Book settings
title: Python slides
author: Thierry Parmentelat
logo: ../media/inria-50-alpha.png

execute:
#  execute_notebooks: cache
  execute_notebooks: force
  exclude_patterns: 
    - _book/**
    - _ipypublish/**
    - _book/_build/jupyter_execute/*
