# Jupyter Book settings

title: Python
author: Thierry Parmentelat
logo: media/logo-python.svg

repository:
  url: https://github.com/flotpython/slides
  branch: main
  path_to_book: slides

html:
  use_repository_button: yes
  use_edit_page_button: yes
  use_issues_button: yes

###

only_build_toc_files: true

execute:
#  execute_notebooks: "force"
  execute_notebooks: cache

sphinx:
  config:
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py:percent

# for raw <img> tags in markdown
parse:
  myst_enable_extensions:
    - html_image
